steps:
        - name: "gcr.io/cloud-builders/go"
          args: ["install", "github.com/{GITHUB_HANDLE}/gato-app"]
          env: ["PROJECT_ROOT=github.com/{GITHUB_HANDLE}/gato-app"]
        - name: "gcr.io/cloud-builders/docker"
          args: ["build", "-t", "gcr.io/{GCP_PROJECT_ID}/gato-app:$REVISION_ID", "-f", "Dockerfile", "."]
          images:
            - "gcr.io/{GCP_PROJECT_ID}/gato-app:$REVISION_ID"
